name: Niveaux
version: 1.0.0
main: enferplugins.niveaux.NiveauxPlugin
api-version: 1.20
description: Système de progression basé sur le temps de jeu
author: Saguime

commands:
  niveau:
    description: Gestion des niveaux des joueurs
    usage: /niveau <add|remove|set|reset> [valeur] <pseudo>
    permission: niveaux.admin
    aliases:
      - n

permissions:
  niveaux.admin:
    description: Accès complet aux commandes de gestion des niveaux
    default: op
