name: EnferNiveaux
version: 1.0.0
main: enferplugins.niveaux.NiveauxPlugin
api-version: 1.20
description: "Systeme de progression base sur le temps de jeu"
author: Saguime

commands:
  niveau:
    description: "Gestion des niveaux des joueurs"
    usage: "/niveau <pseudo> | /niveau <add|remove|set|reset> [valeur] <pseudo>"
    aliases:
      - n

permissions:
  niveaux.admin:
    description: "Acces complet aux commandes de gestion des niveaux"
    default: op
  niveaux.see:
    description: "Consulter le niveau d'un joueur"
    default: true
